### ISSUE TITLE
Implementar situação atual com base em pesquisas e justificar a escolha do tema.

### ISSUE THREAD

**Issue by DanCampos12** [DanCampos12/requirements-divdados#5]
![Image](https://user-images.githubusercontent.com/65630045/187097655-a0fbcf32-db05-4c1d-aad4-f25d99508a22.png)

**Comment by Gabrielclf10** [comment]
**_Algumas referências:_** 

- https://www.organizze.com.br/

- https://play.google.com/store/apps/details?id=com.monefy.app.lite&hl=pt_BR&gl=US

- https://info.minitab.com/pt/resources/meet-minitab-statistical-software-capterra?utm_campaign=Global_PPC-Capterra-MSS-April-2021&utm_source=ppc&utm_medium=Capterra-PT&utm_term=Capterra-PT&utm_content=Capterra-PT
